namespace: qlik
name: sense
version: 0.1.0
readme: README.md
authors:
  - Adam Haydon (https://github.com/ahaydon)
description: Collection of roles for managing Qlik Sense Enterprise deployments
license:
  - MIT
tags:
  - qlik
  - sense
repository: https://github.com/QlikProfessionalServices/ansible-qliksense-collection
documentation: https://github.com/QlikProfessionalServices/ansible-qliksense-collection/wiki
homepage: https://github.com/QlikProfessionalServices/ansible-qliksense-collection
issues: https://github.com/QlikProfessionalServices/ansible-qliksense-collection/issues
build_ignore: []
