---
- name: Check license
  ansible.windows.win_uri:
    url: "https://{{ site_hostname }}/qrs/license?Xrfkey=asdfghjklzxcvbnm"
    headers:
      X-Qlik-Xrfkey: asdfghjklzxcvbnm
      Cookie: "{{ qs_cookie }}"
    return_content: yes
  register: sense_license

- name: Activate license
  ansible.windows.win_uri:
    url: "https://{{ site_hostname }}/qrs/license?Xrfkey=asdfghjklzxcvbnm"
    method: POST
    content_type: application/json
    headers:
      X-Qlik-Xrfkey: asdfghjklzxcvbnm
      Cookie: "{{ qs_cookie }}"
    body:
      key: "{{ site_license_key }}"
      name: "{{ site_license_name }}"
      organization: "{{ site_license_org }}"
    status_code: 201
  changed_when: true
  when: sense_license.json.id is not defined
