---
- name: Include fact tasks
  ansible.builtin.import_tasks: gather_facts.yaml

- name: Include license tasks
  ansible.builtin.import_tasks: license.yaml
  module_defaults:
    ansible.windows.win_uri:
      headers:
        X-Qlik-Xrfkey: "{{ xrfkey }}"
        Cookie: "{{ qs_cookie }}"
