---
db_user: qliksenserepository
db_host: localhost
db_port: 4432
static_content_root_dir: '{{ root_dir | default("") }}\StaticContent'
archived_logs_dir: '{{ root_dir | default("") }}\ArchivedLogs'
apps_dir: '{{ root_dir | default("") }}\Apps'
create_cluster: true
install_local_db: true
configure_db_listener: false
listen_addresses:
  - 127.0.0.1
  - ::1
ip_range:
  - 127.0.0.1/32
  - ::1/128
db_max_conn: 100
http_port_number: 80
https_port_number: 443
enable_http_port: false
db_maximum_connection_pool_size: 90
skip_start_services: false
shared_persistance_config: '{{ ansible_env.TEMP }}\spc.cfg'
