---
- name: Include check tasks
  ansible.builtin.include_tasks:
    file: checks.yaml

- name: Create shared persistence configuration file
  ansible.windows.win_template:
    src: spc.cfg.j2
    dest: "{{ shared_persistance_config }}"

- name: Install Qlik Sense Enterprise Server
  ansible.windows.win_package:
    creates_service: QlikSenseRepositoryService
    path: "{{ setup_path }}"
    arguments:
      - -silent
      - accepteula={{ accept_eula | int }}
      - desktopshortcut={{ desktop_shortcut | int }}
      - skipstartservices={{ update_path is defined | default(skip_start_services) | int }}
      - userwithdomain={{ user_with_domain }}
      - userpassword={{ user_password }}
      - dbpassword={{ db_password }}
      - hostname={{ hostname | default('') }}
      - sharedpersistenceconfig={{ shared_persistance_config | ansible.windows.quote }}
      - senddata={{ send_data | default(0) | int }}
      - skipvalidation={{ skip_validation | default(0) | int }}
      - bundleinstall={{ bundle_install | default([]) | join(',') }}

- name: Upgrade Qlik Sense Enterprise Server
  ansible.windows.win_package:
    path: "{{ setup_path }}"
    arguments:
      - -silent
      - accepteula={{ accept_eula | int }}
      - desktopshortcut={{ desktop_shortcut | int }}
      - skipstartservices={{ update_path is defined | default(skip_start_services) | int }}
      - userpassword={{ user_password }}
      - dbpassword={{ db_password }}
  when:
    - installed_release != ''
    - installed_release != setup_version

- name: Include reboot tasks
  ansible.builtin.include_tasks:
    file: reboot.yaml

- name: Install Qlik Sense update
  ansible.windows.win_package:
    path: "{{ update_path }}"
    arguments:
      - install
      - startservices={{ (not skip_start_services) | default(1) | int }}
  when:
    - update_path is defined
    - installed_patch != update_version

- name: Include service tasks
  ansible.builtin.include_tasks:
    file: start_services.yaml
