---
- name: Include check tasks
  ansible.builtin.include_tasks:
    file: checks.yaml

- name: Include reboot tasks
  ansible.builtin.include_tasks:
    file: reboot.yaml

- name: Install Qlik Sense update
  ansible.windows.win_package:
    path: "{{ update_path }}"
    arguments:
      - install
      - startservices={{ (not skip_start_services) | default(1) | int }}
  when: update_version is version(installed_patch, 'gt')

- name: Include service tasks
  ansible.builtin.include_tasks:
    file: start_services.yaml
