---
- name: Start Repository database
  ansible.windows.win_service:
    name: QlikSenseRepositoryDatabase
    state: started
  when: install_local_db and not skip_start_services

- name: Start Qlik Sense services
  ansible.windows.win_service:
    name: "{{ item }}"
    state: started
  loop:
    - QlikSenseServiceDispatcher
    - QlikSenseRepositoryService
    - QlikSenseProxyService
    - QlikSenseEngineService
    - QlikSenseSchedulerService
    - QlikSensePrintingService
  when: not skip_start_services

- name: Wait for Qlik Sense services to be ready
  ansible.windows.win_uri:
    url: "http://{{ ansible_facts.hostname }}:4444/status/servicestate?xrfkey=asdfghjklzxcvbnm"
    follow_redirects: none
    method: GET
    headers:
      X-Qlik-Xrfkey: asdfghjklzxcvbnm
      X-Qlik-User: UserDirectory=INTERNAL;UserId=sa_api
    return_content: yes
  register: _result
  until: _result.status_code == 200 and _result.json.value > 0
  retries: 30
  delay: 10
  when: not skip_start_services
