---
- name: Start Repository database
  ansible.windows.win_service:
    name: QlikSenseRepositoryDatabase
    state: started
  when: install_local_db and not skip_start_services

- name: Start Qlik Sense services
  ansible.windows.win_service:
    name: "{{ item }}"
    state: started
  loop:
    - QlikSenseServiceDispatcher
    - QlikSenseRepositoryService
    - QlikSenseProxyService
    - QlikSenseEngineService
    - QlikSenseSchedulerService
    - QlikSensePrintingService
  when: not skip_start_services

- name: Wait for Qlik Sense services to start
  ansible.windows.win_uri:
    url: "https://{{ ansible_facts.hostname }}/qps/user"
    follow_redirects: none
    method: GET
    validate_certs: no
  register: _result
  until: _result.status_code == 200
  retries: 30
  delay: 10
  when: not skip_start_services
