---
- name: Firewall rule to allow QRD access from rim nodes
  community.windows.win_firewall_rule:
    name: Qlik Sense Repository Database
    group: Qlik Sense
    localport: "{{ win_firewall_db_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
