---
- name: Firewall rule to allow HTTPS access to Qlik Sense
  community.windows.win_firewall_rule:
    name: Qlik Sense Proxy (HTTPS-In)
    group: Qlik Sense
    localport: 443
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
