---
- name: Firewall rule to allow status checks
  community.windows.win_firewall_rule:
    name: Qlik Sense QRS Status Check
    group: Qlik Sense
    localport: 4444
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
