---
- name: Create Qlik Sense scheduler firewall rules
  community.windows.win_firewall_rule:
    name: "{{ item.name }}"
    localport: "{{ item.port }}"
    group: Qlik Sense
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
  loop:
    - name: Qlik Sense Scheduler Manager
      port: 5050
    - name: Qlik Sense Scheduler Worker
      port: 5151
  loop_control:
    label: "{{ item.name }}"
